TITLE = "Schlangenspiel Online"
WIDTH = 1024
HEIGHT = 768
BILDSCHIRM_SIZE = (WIDTH,HEIGHT)
FPS = 60
BLACK = (0, 0, 0)
GREY = (25, 25, 25)

TILESIZE = 16
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE

PORT = 5558
HOST = 'localhost'
